### ISSUE TITLE
Fade options do not seem to work.

### ISSUE THREAD

**Issue by HugoCortell** [Unity-Technologies/AutoLOD#78] opened 2020-12-15 13:07 UTC
I am certain that I must have set something wrong, I have set my auto LOD to crossfade and yet it still has that pop-in effect.

Am I missing something? What should I do to make crossfades "smoother"?

**Comment by amirebrahimi** [comment] 2020-12-24 18:13
Hi @HugoCortell. To tease out the issue further can you try to see if this is reproducible in a default project in Unity without AutoLOD involved? Please share a video of the issue, too, if possible and the version of Unity you are using.

**Comment by amirebrahimi** [comment] 2021-08-13 22:43
Closing issue since it has not had any recent activity.

**Closed by amirebrahimi** 2021-08-13 22:43 UTC
