### ISSUE TITLE
When deleting the AutoLOD folder, the folder comes back to life

### ISSUE THREAD

**Issue by laurentopia** [Unity-Technologies/AutoLOD#22] opened 2018-03-23 01:36 UTC
it's like a zombie, can't kill it

**Comment by amirebrahimi** [comment] 2018-04-26 00:49
I tried this myself and couldn't reproduce. Are there any folders underneath it? Were you in a scene that had SceneLOD enabled?

**Comment by shazbit** [comment] 2018-08-31 17:55
This happens with plugins that are still loaded. Remove it while the editor is closed.

**Comment by amirebrahimi** [comment] 2018-09-06 00:43
Another person wrote a comment and then deleted it I believe, but I think it may be the answer to your problem -- it's likely you had a DLL in the folder or some other file that was locked that was keeping the directory from being deleted. 

I'm going to close this issue since it has lived for a while. If you encounter it again, then feel free to re-open or create a new issue.

**Closed by amirebrahimi** 2018-09-06 00:43 UTC
Labels: invalid, question
